"""Add experience and index

Revision ID: b5580bd87550
Revises: e4a5b54335c7
Create Date: 2025-12-29 23:10:27.587376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5580bd87550'
down_revision: Union[str, Sequence[str], None] = 'e4a5b54335c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archaeologists', sa.Column('experience_years', sa.Integer(), server_default='0', nullable=True))
    op.create_index('idx_arch_name', 'archaeologists', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_arch_name', table_name='archaeologists')
    op.drop_column('archaeologists', 'experience_years')
    # ### end Alembic commands ###
